name: Spark Flows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PySpark
        run: |
          pip install pyspark pytest

      - name: Run Pytest on Spark Jobs
        run: pytest

